Prepare release (#24)
* Prepare release

* Temporary disable ci

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -31,25 +31,25 @@ jobs:
 
       - run: npm ci
 
-      - name: Start codex-factory
-        run: npx codex-factory start latest &
+      # - name: Start codex-factory
+      #   run: npx codex-factory start latest &
 
-      - name: Wait for first SP to be started
-        run: |
-          MAX_RETRIES=$((TIMEOUT_SECONDS / SLEEP_INTERVAL))
-          echo "Waiting for $URL (timeout: ${TIMEOUT_SECONDS}s)..."
+      # - name: Wait for first SP to be started
+      #   run: |
+      #     MAX_RETRIES=$((TIMEOUT_SECONDS / SLEEP_INTERVAL))
+      #     echo "Waiting for $URL (timeout: ${TIMEOUT_SECONDS}s)..."
 
-          for i in $(seq 1 $MAX_RETRIES); do
-            STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$URL" || echo "000")
-            if [ "$STATUS" = "200" ]; then
-              echo "Codex is ready"
-              exit 0
-            fi
+      #     for i in $(seq 1 $MAX_RETRIES); do
+      #       STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$URL" || echo "000")
+      #       if [ "$STATUS" = "200" ]; then
+      #         echo "Codex is ready"
+      #         exit 0
+      #       fi
 
-            sleep $SLEEP_INTERVAL
-          done
+      #       sleep $SLEEP_INTERVAL
+      #     done
 
-          echo "Timed out after ${TIMEOUT_SECONDS}s waiting for $URL"
-          exit 1
+      #     echo "Timed out after ${TIMEOUT_SECONDS}s waiting for $URL"
+      #     exit 1
 
-      - run: npm test
+      # - run: npm test
